package refactoring.model.buttonnames;

public enum ZoneId {
    UTC_ZERO, UTC_ONE, UTC_TWO, UTC_THREE,
    UTC_FOUR, UTC_FIVE, UTC_SIX,
    UTC_SEVEN, UTC_EIGHT, UTC_NINE,
    UTC_TEN, UTC_ELEVEN, UTC_TWELVE,
    UTC_MINUS_ONE, UTC_MINUS_TWO, UTC_MINUS_THREE,
    UTC_MINUS_FOUR, UTC_MINUS_FIVE, UTC_MINUS_SIX,
    UTC_MINUS_SEVEN, UTC_MINUS_EIGHT, UTC_MINUS_NINE,
    UTC_MINUS_TEN, UTC_MINUS_ELEVEN, UTC_MINUS_TWELVE;
}
